# Generated by Django 5.0.7 on 2026-06-17 11:54

import django.db.models.deletion
import licenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=licenses.models.attachment_upload_path, verbose_name='扫描件')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前有效版本')),
                ('uploaded_by', models.CharField(blank=True, default='系统', max_length=60, verbose_name='上传人')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='版本说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='licenses.license', verbose_name='证照')),
            ],
            options={
                'verbose_name': '证照附件',
                'verbose_name_plural': '证照附件',
                'ordering': ['-version', '-created_at'],
                'unique_together': {('license', 'version')},
            },
        ),
    ]
